version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 6  # Aumentado a 6 para ser más permisivo
  complex-logic:
    enabled: true
    config:
      threshold: 5  # Aumentado para permitir más complejidad
  file-lines:
    enabled: true
    config:
      threshold: 350  # Límite de líneas por archivo
  method-complexity:
    enabled: true
    config:
      threshold: 20  # Umbral más permisivo
  method-count:
    enabled: true
    config:
      threshold: 25  # Aumentado para manejar más métodos por clase
  method-lines:
    enabled: true
    config:
      threshold: 40  # Límite de líneas por método aumentado
  nested-control-flow:
    enabled: true
    config:
      threshold: 5  # Permitir más anidaciones
  return-statements:
    enabled: true
    config:
      threshold: 5  # Permitir más declaraciones de retorno
  similar-code:
    enabled: true
  identical-code:
    enabled: true

exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "venv/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"